import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "../providers/ReactQueryProvider";
import Navbar from "@/componants/navbar/navbar";
import { TokenProvider } from "@/context/TokenContext";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Make root take full viewport and prevent page scroll globally.
  // Auth pages already center content and use full height, so this eliminates stray scrollbars.
  return (
    <html lang="en" className="h-screen overflow-hidden">
      <body className={`${inter.className} h-screen overflow-hidden`}>
        <TokenProvider>
          <ReactQueryProvider>
            <Navbar />
            <Toaster position="bottom-center" reverseOrder={false} />
            {children}
          </ReactQueryProvider>
        </TokenProvider>
      </body>
    </html>
  );
}
