export const TAGS = [
  { id: 3, name: "Sports" },
  { id: 4, name: "Politics" },
  { id: 5, name: "News" },
  { id: 6, name: "Technology" },
  { id: 7, name: "Health" },
  { id: 8, name: "Education" },
  { id: 9, name: "Science" },
  { id: 10, name: "Business" },
  { id: 11, name: "Entertainment" },
  { id: 12, name: "Travel" },
  { id: 13, name: "Food" },
  { id: 14, name: "Lifestyle" },
  { id: 15, name: "Fashion" },
  { id: 16, name: "Art" },
  { id: 17, name: "Culture" },
  { id: 18, name: "History" },
  { id: 19, name: "Music" },
  { id: 20, name: "Movies" },
  { id: 21, name: "Books" },
  { id: 22, name: "Finance" },
  { id: 23, name: "Economy" },
  { id: 24, name: "Environment" },
  { id: 25, name: "Nature" },
  { id: 26, name: "Animals" },
  { id: 27, name: "Fitness" },
  { id: 28, name: "DIY" },
  { id: 29, name: "Parenting" },
  { id: 30, name: "Career" },
  { id: 31, name: "Self-Improvement" },
  { id: 32, name: "Relationships" },
  { id: 33, name: "Gaming" },
  { id: 34, name: "Photography" },
  { id: 35, name: "Automotive" },
  { id: 36, name: "Real Estate" },
  { id: 37, name: "Marketing" },
  { id: 38, name: "Startups" },
  { id: 39, name: "Programming" },
  { id: 40, name: "AI" },
  { id: 41, name: "Machine Learning" },
  { id: 42, name: "Cybersecurity" },
];
